staging:
  profile: ~
  whoami: release/2.24.1-site-stg-out
  subdir: content/log4j/2.24.1


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 27465
# - Commit ID: a9541e06f97a8d8356c81861b9833eda4a3d792b
# - Timestamp: 2024-09-23T21:07:36Z
